import type { Metadata } from "next";
import { Inter,Roboto_Condensed } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/NavBar";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Condensed({
  subsets:['latin'],
  variable:'--font-roboto',
  weight:'400'
})
export const metadata: Metadata = {
  title: "Aymen Bouchali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme) {
                    document.documentElement.setAttribute('data-theme', theme);
                  } else {
                    var systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                    document.documentElement.setAttribute('data-theme', systemTheme);
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`${roboto.variable} font-roboto bg-theme-bg-primary text-theme-text-primary transition-colors duration-300`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
