import type { Metadata } from "next";
import { Inter,Roboto_Condensed } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/NavBar";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Condensed({
  subsets:['latin'],
  variable:'--font-roboto',
  weight:'400'
})
export const metadata: Metadata = {
  title: "Aymen Bouchali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {` ${roboto.variable} font-roboto bg-gradient-to-r from-black via-blue-950 to-black text-white`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
